### ISSUE TITLE
fine-tune the slowfast ava model

### ISSUE THREAD

**Issue by o5786486** [FabiTheGabi/VideoProcessMining#2]
Hi @FabiTheGabi ,Thanks for  creating this code its very helpful!!!
My custom dataset is in 6 classes 
I want to fine-tune the slow fast ava model (SLOWFAST_32x2_R101_50_50.pkl) 80 class to 6 class
Then i get the error:
`[INFO: checkpoint.py:  488]: Load from given checkpoint file.
[03/03 03:34:28][INFO] slowfast.utils.checkpoint:  488: Load from given checkpoint file.
Traceback (most recent call last):
  File "/home/ian/code/VideoProcessMining-master/app_gui/demo_window.py", line 94, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ian/code/VideoProcessMining-master/app_gui/demo_window.py", line 1157, in launch_training_from_worker
    launch_job(cfg=self.cfg, init_method="tcp://localhost:9999", func=train)
  File "/home/ian/code/VideoProcessMining-master/slowfast/utils/misc.py", line 282, in launch_job
    func(cfg=cfg)
  File "/home/ian/code/VideoProcessMining-master/tools/train_net.py", line 401, in train
    start_epoch = cu.load_train_checkpoint(cfg, model, optimizer)
  File "/home/ian/code/VideoProcessMining-master/slowfast/utils/checkpoint.py", line 496, in load_train_checkpoint
    cfg=cfg,
  File "/home/ian/code/VideoProcessMining-master/slowfast/utils/checkpoint.py", line 281, in load_checkpoint
    ms.load_state_dict(checkpoint["model_state"])
  File "/home/ian/.conda/envs/slowfast/lib/python3.6/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SlowFast:
        size mismatch for head.projection.weight: copying a param with shape torch.Size([80, 2304]) from checkpoint, the shape in current model is torch.Size([6, 2304]).
        size mismatch for head.projection.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([6]).`

Here is my train option:
https://imgur.com/Zx7AZ4o

Where did I go wrong? and how can i fix it?
sorry for the poor english
Thank you!

**Comment by FabiTheGabi** [comment]
Hi @o5786486,

In my opinion your selected model is meant for inference only (https://github.com/facebookresearch/SlowFast/issues/141). So just test it with one of the models proposed in the example config files.

If this does not work, please also attach the complete log in addition to your question :)

Best regards

**Comment by o5786486** [comment]
Hi @FabiTheGabi 
thanks for replying!
I got a other error during training when I use softmax + cross_entropy



File "/home/ian/code/VideoProcessMining-master/slowfast/utils/misc.py", line 282, in launch_job
    func(cfg=cfg)
  File "/home/ian/code/VideoProcessMining-master/tools/train_net.py", line 476, in train
    train_loader, model, optimizer, train_meter, cur_epoch, cfg, writer
  File "/home/ian/code/VideoProcessMining-master/tools/train_net.py", line 88, in train_epoch
    loss = loss_fun(preds, labels)
  File "/home/ian/.conda/envs/slowfast/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ian/.conda/envs/slowfast/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 932, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/ian/.conda/envs/slowfast/lib/python3.6/site-packages/torch/nn/functional.py", line 2317, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/ian/.conda/envs/slowfast/lib/python3.6/site-packages/torch/nn/functional.py", line 2113, in nll_loss
    .format(input.size(0), target.size(0)))
ValueError: Expected input batch_size (30) to match target batch_size (32).

Where did I go wrong?
I did not change any code

**Comment by FabiTheGabi** [comment]
HI @o5786486,

could you please append the log-file (stdout.log) as described in https://github.com/FabiTheGabi/VideoProcessMining/blob/master/slowfast/datasets/DATASET.md.

This would help very much in tracing the steps that lead to your problem.

Thank you a lot.
